Done navbar
Design-ITUS-HCMUS/admin pull request #10
Opened 2024-02-01 16:59 UTC by southsea2410

- Add `CssBaseline` in `layout.tsx` (CssBaseline is equal to `global.css`)
- The `CssBaseline` setting is in theme.ts
- Add Navbar and its Story

2024-02-02 05:00 UTC, NganTrucLe requested changes

2024-02-02 10:24 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +            variant='temporary'
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/1098008c-5e4b-4a19-93cd-e20c05e2f06d)
default đã 'temporary' rồi nha, nên xóa dòng này

2024-02-02 10:36 UTC, vmathu requested changes

2024-02-02 10:36 UTC, vmathu commented on src/libs/ui/components/Navbar.tsx
> +        endIcon={menuItems && (open ? <ExpandMoreIcon /> : <ExpandLessIcon />)}>
check lại des nko tại vì chỉ có icon xuống hoi hong quan tâm open hay k đâu

2024-02-02 10:43 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +            PaperProps={{ sx: { width: '100%' } }}>
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/846e34d6-a238-4ffc-be87-86b8a829842c)
nó đã có default là 'temporary' rồi nhe nên mình bỏ dòng variant đi.
Tắt keepMounted đi, vì nó làm web phải load nhiều hơn, khi nào bấm vào thì mới cho nó load cái drawer lên, ở docs Drawer nó có bảo là `keepMounted` là mặc định, nên phải chỉnh false lại, chỉnh bằng cách sửa PaperProps nha 
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/80c0cec3-8766-4f26-a21a-28393f9b45e0)
https://mui.com/material-ui/react-drawer/

2024-02-02 11:35 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +}
```
function UserSettings(settings: INavBarItem): React.JSX.Element {
  const [anchorElUser, setAnchorElUser] = React.useState<null | HTMLElement>(null);
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));

  const handleOpenUserMenu = (event: React.MouseEvent<HTMLElement>) => {
    !isMobile && setAnchorElUser(event.currentTarget);
  };

  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };

  return (
    <div>
      <ListItemButton
        onClick={handleOpenUserMenu}
        component={isMobile ? 'div' : Link}
        href={isMobile? '/profile' : ''}
        >
        <Typography variant='subtitle1' fontWeight={700}>
          {settings.name}
        </Typography>
        <ListItemIcon>
          { isMobile ? <ChevronRightIcon /> : <ExpandMoreIcon />}
        </ListItemIcon>
      </ListItemButton>
      {isMobile &&         
      <Menu
        anchorEl={anchorElUser}
        keepMounted
        open={Boolean(anchorElUser)}
        disableScrollLock
        onClose={handleCloseUserMenu}>
        {settings.menuItems?.map(
          (item, i, arr) =>
            i < arr.length - 1 && (
              <MenuItem key={item.name} onClick={handleCloseUserMenu}>
                {item.icon && <ListItemIcon>{item.icon}</ListItemIcon>}
                <ListItemText>
                  <Link href={item.link}>{item.name}</Link>
                </ListItemText>
              </MenuItem>
            )
        )}
        <Divider />
        <MenuItem key={settings.menuItems?.[settings.menuItems?.length - 1].link}>
          <ListItemText sx={{ color: colors.notification['error'] }}>
            <Link href={settings.menuItems?.[settings.menuItems?.length - 1].link || '#'}>
              {settings.menuItems?.[settings.menuItems?.length - 1].name}
            </Link>
          </ListItemText>
        </MenuItem>
      </Menu>
      }
    </div>
  );
}
```
- Theo design thì cái chỗ User Settings define riêng component, không dùng button cho nên mình không lấy button của MUI được, nó có một số state cũng xấu lắm, mà override thì dài, nên t thay bằng `ListItemButton` nha. 
- Cũng không có handle cái icon switch qua lại giữa ExpandMore với ExpandLess nè.
- Handle kèm theo mấy cái isMobile để nó chọn lọc render responsive và để tận dụng dùng lại trong drawer luôn.

2024-02-02 11:35 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +                </Button>
`<UserSettings {...settings} />`
Như có nói ở trên, đã tách component cho profile rồi nên phần này replace luôn cái component đó nè

2024-02-02 11:35 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +}
Ngoài ra thì t có thay <Box> bằng <div>, vì load nhanh hơn https://mui.com/system/getting-started/usage/, nhma nếu có styling gì nữa thì đổi thành Styled Component nha

2024-02-02 11:35 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +            </div>
Xóa `div` nè

2024-02-04 03:38 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +import styled from '@mui/material/styles/styled';
hôm qua viết docs thì t có phát hiện thêm cái này, không import 3rd level nhe, có j m bổ sung vô eslint luôn cho nó quét tránh sót https://mui.com/material-ui/guides/minimizing-bundle-size/

2024-02-06 12:32 UTC, southsea2410 commented
Comment added

2024-02-06 15:59 UTC, NganTrucLe reviewed
Oke refactor một số chỗ thui là oke rồi.
Còn hiện giờ t thấy những thông tin như navbar items, pages, user settings ấy, nó lun lun fix cứng, cố định chứ cũng hem có thằng nào truyền props vô hết. Nên m có thể nghĩ tới hướng để constant những cái đó lun nha, cho cái NavBar k có props nào í :> Với đỡ mấy cái syntax ? null đồ
Ngoài ra thì chắc thêm background cho nav bar màu trắng, chứ sao bên t nó xám nhạt nhòa lắm m ơi, kiểu so sánh với cái paper ở dưới nè
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/d0db63e4-680b-495c-9d78-7802159c68ea)

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +interface INavBarItem {
Òm đổi NavbarPill lun ik cho đồng bộ hết

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +}));
này oke, nhma m đã forward cái prop active rùi í, 2 cái nó chỉ khác nhau ở dòng colors. neutral[400] với backgroundColor hui í, nên gộp chung ik cho gọn

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +      )}
Gộp styled component ở trên rồi ở dưới đặt cái prop active vô hoiii

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +          {menuItems?.map(
Bỏ chấm hỏi ik, tại đã dùng` menuItems &&` rùi á

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +          {menuItems && (
Này cũng vậy nè, menuItems && bên trong menuItems && hẻ

2024-02-06 15:59 UTC, NganTrucLe commented on src/libs/ui/components/Navbar.tsx
> +  }));
Tưởng mí styled component này đem ra ngoài hết, vì lỡ nó có crack behavior é

2024-02-07 03:15 UTC, NganTrucLe approved these changes

2024-02-07 08:24 UTC, vmathu approved these changes

2024-02-07 08:24 UTC, merged