OSW-19: [FE] Sign in/sign up & Layouts & Routing with no re-render layout
Design-ITUS-HCMUS/admin pull request #12
Opened 2024-02-02 10:01 UTC by NhanHoPeter217

- UI and responsive for Sign in/Sign up
- Route Groups, Organization Routing
- Share layout between multiple pages (On navigation, layouts preserve state, remain interactive, and do not re-render.)

2024-02-02 13:02 UTC, NganTrucLe reviewed
Tất cả component thiếu stories

2024-02-02 13:02 UTC, NganTrucLe commented on src/app/styles.tsx
> +      </Typography>
muốn thì định nghĩa bên theme.ts một variant nhé, tương tự Hải Nam, xóa letterSpacing đi

2024-02-02 13:02 UTC, NganTrucLe commented on src/app/styles.tsx
> +};
Theo tui không tách component này nha :)))) nếu muốn dùng đi dùng lại thì có thể để tiếp tục để trong layout nha, không biết @vmathu thấy sao

2024-02-02 13:02 UTC, NganTrucLe commented on src/app/(auth)/sign-in/page.tsx
> +  const isSmallScreen = useMediaQuery(`(max-width: ${constants.PAPER_MAX_WIDTH})`);
Không dùng kiểu này à nha :))) responsive theo breakpoints device nha để có sự tổng quát, không responsive theo width của cái card

2024-02-02 13:07 UTC, vmathu requested changes

2024-02-02 13:07 UTC, vmathu commented on src/app/components/index.tsx
components bên libs/ui í s lại để trong app dị

2024-02-02 13:07 UTC, vmathu commented on src/app/components/OTPInput.tsx
> +    <Box style={otpGroup}>
đc thì thử `<Grid>` i

2024-02-02 13:09 UTC, vmathu commented on src/app/styles.tsx
> +};
đang nghĩ là làm layout gồm cả card lun nha :'))

2024-02-03 10:06 UTC, NhanHoPeter217 commented on src/libs/ui/components/PasswordFieldWithLabel.tsx
> +    const togglePasswordVisibility = () => setShowPassword((prev) => !prev);
À tại quen tay kĩ TH out of sync xíu thoi, nhma chắc chỗ này k sao, để sửa lại cho gọn :">

2024-02-03 10:07 UTC, NhanHoPeter217 commented on src/app/_app.tsx
deleted

2024-02-05 04:54 UTC, NganTrucLe commented on src/app/(auth)/sign-in/otp/page.tsx
Hôm qua Duy Quân có nói nên tui coi lại thì de, OTP không nằm trong sign in nha, nó là 1 bước của forget password á, có gì cho hiện prototype nhe. Router structure tui expect thì nó nên như thế này 
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/74257e16-f94f-4455-a2ab-9518221d4804)
Tức là change password và forget nằm bên trong sign-in á, còn otp nằm trong forget

2024-02-05 04:54 UTC, NganTrucLe commented on src/app/(auth)/_components/CardHeader.tsx
> +import { CardProps, HeaderStyle } from '.';
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/d3e299be-1324-48cc-bd53-3b33c1c97fa6)
Chỗ nì á, đem từ HeaderStyle để vô trong file này lun đi cho dễ quản, mình làm styled component lunn, hok thì viết sx prop của Typography ấy, không có cần đặt thêm div ở ngoài đâu

2024-02-05 04:54 UTC, NganTrucLe commented on src/app/(auth)/_components/CardPage.tsx
> +};
khúc này oke nè, nhma tách hẳn file component lun đi Nhân.

2024-02-05 04:54 UTC, NganTrucLe commented on src/app/(auth)/_components/CardPage.tsx
> +              fontWeight: '600',
`sx` prop nhe

2024-02-05 04:54 UTC, NganTrucLe commented on src/app/(auth)/_components/CardPage.tsx
> +          </Link>
```
<Typography 
     component={Link} 
     href={footerLinkHref || ''} 
     variant='linkPrimary' 
     sx={{ display: 'inline-block', width: 'fit-content'}}
>
     {footerLinkText}
</Typography>
```

2024-02-05 04:54 UTC, NganTrucLe commented on src/libs/ui/components/OTPInput.tsx
> +    <Box style={otpGroup}>
bỏ inline style, dùng component `<Stack>`, Stack là dạng display flex, có chỉnh được direction lunnn, thay cho cái Grid nhe, cũng bỏ được mấy cái `mr, ml` thì phải, tại `display: flex` nó có trường gap á. Để `gap: 1` là tương đương.
Còn lại thì oke

2024-02-05 04:54 UTC, NganTrucLe commented on src/libs/ui/components/PasswordFieldWithLabel.tsx
> +};
đừng inline style nheeee, styled component hay là sx prop đi nè 😢 
Còn lại oke r

2024-02-05 04:56 UTC, NganTrucLe commented on src/app/(auth)/_components/CardPage.tsx
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/97326103/f62a0780-4e41-416c-9259-07d5e6b3f896)
Chỉnh bố cục của cái component CardPage như này nhe

2024-02-05 07:06 UTC, vmathu requested changes

2024-02-05 07:06 UTC, vmathu commented on src/app/(auth)/_components/CardPage.tsx
ye í t của làm layout là vẫn truyền children dzo á lmao 🐧 chứ k phải truyền mỏi props dou :")) body khác nhao mò

2024-02-05 16:50 UTC, NganTrucLe commented on src/app/(auth)/_components/CardHeader.tsx
> +
Thấy dòng này dư thì phải, do đâu thấy dùng ở trong này

2024-02-05 16:50 UTC, NganTrucLe commented on src/app/(auth)/_components/CardPage.tsx
> +  );
hoi để lại cái footer rồi bật tắt ik, thấy hợp nhí mè 😢

2024-02-05 16:50 UTC, NganTrucLe commented on src/app/(auth)/_components/CountDown.tsx
> +
1 dòng thui

2024-02-05 16:50 UTC, NganTrucLe commented on src/app/(auth)/sign-up/page.tsx
> +const SignUp = () => {
Chắc đổi tất cả những cái component chính thành dạng `function SignUpPage() {}` hết nha, đồng bộ cả team lun bữa có họp thì nói với Nam rồi mà hem có ông á :)))

2024-02-05 16:50 UTC, NganTrucLe commented on src/app/(auth)/sign-up/page.tsx
> +};
Test lại nha, chứ tui code bên trang events cũng có layout nè, thì nó tự nhận mà, đâu có khai báo chi

2024-02-06 02:02 UTC, vmathu commented on src/libs/ui/theme.ts
> +            fontWeight: '400',
k có define fontWeight cho variant trong theme á

2024-02-06 02:14 UTC, vmathu requested changes

2024-02-06 02:14 UTC, vmathu commented on src/libs/ui/theme.ts
> +          },
k có define lại variant của typo như này á, chữ cùng h5 nhma có thể khác fontWeight vs color mà, chỗ nào khác này thì !important hả 🐧

2024-02-06 02:36 UTC, vmathu requested changes

2024-02-06 02:36 UTC, vmathu commented on src/app/(auth)/_components/CardPage.stories.tsx
check lại file này nha bên t lỗi í
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/91612623/4ef21126-d566-46fc-a8fd-76607bb9e525)
![image](https://github.com/Design-ITUS-HCMUS/admin/assets/91612623/339482d9-381c-4471-b3be-57317716b6d0)

2024-02-07 09:08 UTC, vmathu approved these changes

2024-02-07 09:09 UTC, NganTrucLe approved these changes

2024-02-07 09:09 UTC, merged