OSW-29: [FE] Accounts management
Design-ITUS-HCMUS/admin pull request #28
Opened 2024-02-20 06:54 UTC by NganTrucLe

- Add UI accounts management page
- React query to handle fetch
- Redux to set a global toast
- Experiment in 
There are some issues:
- Flicker in rendering UI, you must wait a second to see new changes. There might be a bug in FE cache of nextjs because right now data is sent from backend with refetch and invalidate logic.
- Haven't had some stories
- Comment out the fetch query in change password, only left a slot for easily changing in the future.

2024-02-21 03:19 UTC, vmathu requested changes

2024-02-21 04:26 UTC, southsea2410 commented
#### Comment
- Với React Query và Redux Toast thì t thấy nó hoạt động oke, còn về logic code ch hiểu lắm, để nghiên cứu sau.
#### Bổ sung thêm
chắc là buổi họp sắp tới bàn về file `models.ts` và folder `/interfaces`, òm thì chắc là:
- Frontend cũng phải define các "service" để lấy/update data nữa hả 🥲 (folder `/query` ấy)
- Chỉ rõ chức năng của `/interfaces` là cho FE hay BE
- Vị trí bỏ `type` cho React-Query, Context (`models.ts`, `enum.ts`  hay chỗ khác)...
- Liệu có cách nào để bớt gõ lại các type/interface có sẵn hêm :v

2024-02-21 04:31 UTC, southsea2410 reviewed
#### Comment
Với React Query và Redux Toast thì t thấy nó hoạt động oke, còn về logic code ch hiểu lắm, để nghiên cứu sau.
#### Bổ sung thêm
chắc là buổi họp sắp tới bàn về file `models.ts` và folder `/interfaces`, òm thì chắc là:
- Frontend cũng phải define các "service" để lấy/update data nữa hả 🥲 (folder `/query` ấy)
- Chỉ rõ chức năng của `/interfaces` là cho FE hay BE
- Vị trí bỏ type cho React-Query, Context (`models.ts, enum.ts` hay chỗ khác)...
- Liệu có cách nào để bớt gõ lại các type/interface có sẵn hêm :v

2024-02-21 04:56 UTC, NganTrucLe commented on src/utils/enum.ts
> +
Bữa t có raise lên cái này nè, DQuan bảo nếu mình gắt gao đến v thì nó đổi lun, t thì bth nên thoi const object cũm đc :'> chưa thấy có j khác biệt

2024-02-21 05:46 UTC, NganTrucLe commented on src/app/profile/_components/BasicInfo.tsx
> +                </LocalizationProvider>
oke vậy để t wrap thêm nha. Tại vì bên cái cũ t có cái profile.dob rùi í nên là t copy paste lun cho lẹ nên k có để ý

2024-02-21 05:50 UTC, NganTrucLe commented on src/libs/ui/components/Message.tsx
> +        <Progress color={`${progressColors[toast.alert]}`} />
dè t nhớ là phải để vậy ép kiểu chứ k nó k lên thì phải :">

2024-02-21 06:01 UTC, NganTrucLe commented on src/app/profile/page.tsx
> +  ];
tại sideBarItems nó đc truyền vô sideBar là 1 component khác í nên t vẫn giữ sideBarItems chứ lúc code có thấy 😢

2024-02-21 06:09 UTC, southsea2410 commented on src/app/profile/_components/BasicInfo.tsx
> +                </LocalizationProvider>
Ừa, và với mấy cái liên quan tới năm sinh thì bật `disableFuture` lên hẻ, coi như UI không thể chọn được tương lai luôn, theo [docs](https://mui.com/x/api/date-pickers/date-time-picker/#date-time-picker-prop-disableFuture)

2024-02-21 06:13 UTC, southsea2410 commented on src/utils/enum.ts
> +
t cũng hem thấy gì khác biệt, enum thì ngắn với dễ đọc hơn hả, th kệ

2024-02-21 10:23 UTC, southsea2410 commented on src/app/profile/_components/BasicInfo.tsx
File này vẫn bị lỗi cache NextJS, hết cứu

2024-02-23 02:20 UTC, vmathu approved these changes

2024-02-23 02:21 UTC, merged